apiVersion: v1
kind: Namespace
metadata:
  name: miweb-namespace

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: miweb-deployment
  namespace: miweb-namespace
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 1 
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: rengifolu/miweb:BUILD_NUMBER
        ports:
        - containerPort: 80
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: miweb-service 
  namespace: miweb-namespace
spec: 
  selector: 
    app: angular 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 31000 
  type: NodePort 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: miweb-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: angular-192.168.99.102.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: miweb-service
          servicePort: 80
      # - path: /user-service
      #   backend:
      #     serviceName:
      #     servicePort: